name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - "lambda/"

jobs:
  deploy-lambda: # name of our job
    runs-on: ubuntu-latest # Sets or specifies the runner
    steps:
      - name: Checkout code # Corrected from 'users' to 'uses'
        uses: actions/checkout@v2

      - name: Set Up Python # Sets up our python env.
        uses: actions/setup-python@v2
        with:
          python-version: "3.12" # Corrected version format

      - name: Install Dependencies # Installs any packages
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: Configure AWS Creds # Sets up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }} # Corrected from 'aws-access-secret-key'
          aws-region: us-east-2

      - name: Deploy Lambda Function # Zips lambda directory and updates lambda function
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip
